# Generated by Django 2.2.1 on 2019-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='receiverID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='email',
            name='senderID',
            field=models.CharField(max_length=20),
        ),
    ]
