# Generated by Django 2.2.1 on 2019-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0003_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='receiverID',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='draft',
            name='isEncrypto',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
