# Generated by Django 2.2.1 on 2019-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0004_auto_20190618_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='receiver',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiverID',
            field=models.CharField(max_length=50),
        ),
    ]
