# Generated by Django 2.2.1 on 2019-06-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=80)),
                ('c_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=20, unique=True)),
                ('u_name', models.CharField(max_length=80, unique=True)),
                ('u_pwdhash', models.CharField(editable=False, max_length=128)),
                ('salt', models.CharField(editable=False, max_length=64)),
                ('role', models.CharField(choices=[('ST', 'student'), ('TC', 'teacher')], default='ST', max_length=2)),
                ('sex', models.CharField(choices=[('BY', 'boy'), ('GL', 'girl')], default='BY', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=11)),
                ('birth', models.DateField()),
                ('dept', models.CharField(max_length=80)),
                ('last_login', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_cnt', models.IntegerField(default=0)),
                ('grades', models.DecimalField(decimal_places=1, max_digits=4)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.User')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='c_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.User'),
        ),
    ]
